Added Available Help-Channels to /help-guidelines
Java-Discord/JavaBot pull request #240
Opened 2022-03-13 13:46 UTC by MoonTM-GIT

I've added an overview of available help-channels to the `/help-guidelines` command.
Closes #236 

![image](https://user-images.githubusercontent.com/66334318/158062447-1e40acc3-5049-4fc8-9aad-5e38fe1d4d19.png)

2022-03-13 14:55 UTC, DynxstyGIT requested changes

2022-03-13 14:55 UTC, DynxstyGIT commented on src/main/java/net/javadiscord/javabot/systems/help/HelpGuidelinesCommandHandler.java
> +		for(GuildChannel channel:Bot.config.get(event.getGuild()).getHelp().getOpenChannelCategory().getChannels()) {
```suggestion
		for (GuildChannel channel : Bot.config.get(event.getGuild()).getHelp().getOpenChannelCategory().getChannels()) {
```

2022-03-13 15:15 UTC, MoonTM-GIT commented on src/main/java/net/javadiscord/javabot/systems/help/HelpGuidelinesCommandHandler.java
> +		for(GuildChannel channel:Bot.config.get(event.getGuild()).getHelp().getOpenChannelCategory().getChannels()) {
![image](https://user-images.githubusercontent.com/66334318/158066482-b2892a35-5ac8-4cd7-b3f8-e704657fc198.png)

2022-03-13 15:16 UTC, MoonTM-GIT commented on src/main/java/net/javadiscord/javabot/systems/help/HelpGuidelinesCommandHandler.java
> +		for(GuildChannel channel:Bot.config.get(event.getGuild()).getHelp().getOpenChannelCategory().getChannels()) {
![image](https://user-images.githubusercontent.com/66334318/158066521-44591288-284c-4995-a191-5614fcd09a64.png)

2022-03-14 10:22 UTC, DynxstyGIT approved these changes

2022-03-14 10:22 UTC, merged