fix issues detected using Spotbugs and similar tooling
Java-Discord/JavaBot pull request #274
Opened 2022-05-02 17:48 UTC by danthe1st

This PR applies the following fixes:

- remove lombok's `@Slf4j` annotation where the `log` field isn't used
- don't run the same comparison multiple times in an expression (replace `!content.first().isBlank() && !content.first().isBlank()` with `!content.first().isBlank() && !content.second().isBlank()` in `GitHubLinkListener`)
- don't use non-`static` instances for accessing `static` methods
- use `try`-with-resources blocks in order to close resources (preventing resource leaks)
- don't initialize `static` variables in constructors
- remove unused methods

These issues were detected using SpotBugs and EJC (Eclipse Java Compiler).

2022-05-02 17:51 UTC, DynxstyGIT requested changes

2022-05-02 17:51 UTC, DynxstyGIT commented on src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
> +		try(Scanner scan=new Scanner(new URL("https://raw.githubusercontent.com/DevSpen/scam-links/master/src/links.txt").openStream()).useDelimiter("\\A")) {
```suggestion
		try (Scanner scan = new Scanner(new URL("https://raw.githubusercontent.com/DevSpen/scam-links/master/src/links.txt").openStream()).useDelimiter("\\A")) {
```

2022-05-02 17:51 UTC, DynxstyGIT commented on src/main/java/net/javadiscord/javabot/systems/commands/SearchCommand.java
> +		try(Scanner scan=new Scanner(connection.getInputStream()).useDelimiter("\\A")){
```suggestion
		try (Scanner scan = new Scanner(connection.getInputStream()).useDelimiter("\\A")){
```

2022-05-02 19:08 UTC, MoonTM-GIT approved these changes

2022-05-03 06:44 UTC, DynxstyGIT approved these changes

2022-05-03 06:44 UTC, merged