Moved leaderboards to single command
Java-Discord/JavaBot pull request #275
Opened 2022-05-02 18:52 UTC by MoonTM-GIT

This PR moves all leaderboards to a single command to make it a bit easier to find them. I have not made any changes to the commands, I just moved them

2022-05-04 10:27 UTC, danthe1st requested changes
This PR wrongly adds a change in functionality.
The `page` argument from the `help-xp` subcommand is removed but still used in the subcommand handler.
The `page` option should be kept in the leaderboard command configuration file.

2022-05-04 10:27 UTC, danthe1st commented on src/main/resources/commands/slash/user.yaml
> +      name: help-xp
```suggestion
      name: help-xp
      options:
        - name: page
          description: The page of results to show. By default it starts at 1.
          type: INTEGER
          required: false
```

2022-05-04 18:49 UTC, danthe1st approved these changes

2022-05-06 18:18 UTC, DynxstyGIT approved these changes

2022-05-06 18:18 UTC, merged