role-specific emojis
Java-Discord/JavaBot pull request #369
Opened 2022-11-05 16:34 UTC by danthe1st

This PR adds a commend for creating role-exclusive emojis.
![image](https://user-images.githubusercontent.com/34687786/200131010-b893ff12-e3c8-4a98-abde-4049b96e8eff.png)
![image](https://user-images.githubusercontent.com/34687786/200131052-4abf0993-abe7-431a-83e7-516c8f2e0159.png)

2022-11-05 16:36 UTC, DynxstyGIT commented
I'd sugget renaming the command to something like `/emoji-admin add` to fit with the rest of our commands
looks great otherwise

2022-11-05 16:52 UTC, danthe1st commented
> I'd suggest renaming the command to something like `/emoji-admin add` to fit with the rest of our commands looks great otherwise

Done

2022-11-05 16:53 UTC, danthe1st commented
Also note that I wrote the command so it requires `ADMINISTRATOR` permissions and the admin role.

2022-11-05 17:42 UTC, DynxstyGIT requested changes

2022-11-05 17:42 UTC, DynxstyGIT commented on src/main/java/net/javadiscord/javabot/systems/staff_commands/role_emoji/RoleEmojiCommand.java
> +		SlashCommandData slashCommandData = Commands.slash("emoji-admin", "Adds an emoji only usable only with certain roles")
Change the description of the top-level command to something like "Administrative command for managing server emojis"

2022-11-05 17:50 UTC, DynxstyGIT approved these changes

2022-11-06 09:59 UTC, liquiddevelopmentnet approved these changes

2022-11-06 10:39 UTC, merged