create thread for QOTW review
Java-Discord/JavaBot pull request #387
Opened 2023-01-27 19:45 UTC by danthe1st

This PR automatically creates a thread when QOTW review starts.
This thread then contains all review requests.
![image](https://user-images.githubusercontent.com/34687786/215182951-a05ae85f-18e3-4cd3-ad77-3767427633b1.png)

2023-01-27 20:11 UTC, liquiddevelopmentnet approved these changes

2023-01-29 16:24 UTC, MoonTM-GIT requested changes

2023-01-29 16:24 UTC, MoonTM-GIT commented on src/main/java/net/javadiscord/javabot/systems/qotw/submissions/subcommands/QOTWReviewSubcommand.java
> +			Responses.success(event.getHook(), "Submission Accepted", "Successfully accepted submission by " + author.getAsMention()).queue();
This message is sent regardless of the submission actually being accepted or not

2023-01-29 16:32 UTC, MoonTM-GIT approved these changes

2023-01-29 16:34 UTC, merged