Change minimum xp for daily removal to 1
Java-Discord/JavaBot pull request #476
Opened 2024-01-16 14:31 UTC by liquiddevelopmentnet

This PR changes the amount of minimum XP that has to be removed daily from `5` to `1`.
@danthe1st

2024-01-16 18:02 UTC, danthe1st approved these changes
It would e nice if you could also add options for the minimum XP and maximum XP in the `HelpConfig` and initialize them with 1 and 50 respectively.

2024-01-26 11:00 UTC, danthe1st requested changes
Please check the changes I proposed in https://github.com/liquiddevelopmentnet/JavaBot/pull/1.
If these are merged, this PR should automatically update.

2024-01-26 11:05 UTC, danthe1st approved these changes

2024-01-26 20:39 UTC, MoonTM-GIT approved these changes

2024-01-26 20:44 UTC, merged